### ISSUE TITLE
Is it possible to make hls without re-encode?

### ISSUE THREAD

**Issue by abuharsky** [jprjr/icecast-hls#2]
input icecast AAC 96kbps, how to configure it to get HLS with artist-title metadata without re-encode?

**Comment by jprjr** [comment]
At this time no - but I could look into it

Recommend making a FLAC stream and using that for input, to reduce quality loss from re-encoding

**Comment by abuharsky** [comment]
I need to restream 100-150 streams, so, re-encoding use more cpu

**Comment by jprjr** [comment]
This is now possible with v1.0.0 - https://github.com/jprjr/icecast-hls/releases/tag/v1.0.0

Using a config like

```ini
[source.aac]
input = curl
url = http://icecast.example.com:8000/stream

demuxer = avformat
bitstream filters = aac_adtstoasc

decoder = passthrough

[destination.aac]
source = aac
encoder = passthrough
muxer = packed-audio
output = folder
folder = /path/to/some-folder
```

Recommend using the `packed-audio` muxer - an existing AAC Icecast stream is going to be using ADTS format and missing needed metadata for a proper MP4.
