### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Deroyaz** [jprjr/icecast-hls#3]
Hi,
Am having the below error when i run make command on ubuntu server 18.04.5 LTS. Please help

cc -Wall -Wextra -g -O3   -c -o src/ini.o src/ini.c
cc -Wall -Wextra -g -O3   -c -o src/map.o src/map.c
cc -Wall -Wextra -g -O3   -c -o src/main.o src/main.c
src/main.c: In function ‘main’:
src/main.c:175:14: warning: unused parameter ‘argc’ [-Wunused-parameter]
 int main(int argc, const char* argv[]) {
              ^~~~
cc -Wall -Wextra -g -O3   -c -o src/membuf.o src/membuf.c
cc -Wall -Wextra -g -O3 -c -o src/miniflac.o src/miniflac.c
cc -Wall -Wextra -g -O3 -c -o src/minifmp4.o src/minifmp4.c
cc -Wall -Wextra -g -O3   -c -o src/decoder.o src/decoder.c
cc -Wall -Wextra -g -O3 -DDECODER_PLUGIN_AVCODEC=1 -c -o src/decoder_plugin.o src/decoder_plugin.c
cc -Wall -Wextra -g -O3 -c -o src/decoder_plugin_miniflac.o src/decoder_plugin_miniflac.c
cc -Wall -Wextra -g -O3   -c -o src/destination.o src/destination.c
cc -Wall -Wextra -g -O3   -c -o src/destinationlist.o src/destinationlist.c
cc -Wall -Wextra -g -O3   -c -o src/destination_sync.o src/destination_sync.c
cc -Wall -Wextra -g -O3   -c -o src/encoder.o src/encoder.c
cc -Wall -Wextra -g -O3  -DENCODER_PLUGIN_AVCODEC=1 -DENCODER_PLUGIN_EXHALE=1 -DENCODER_PLUGIN_FDK_AAC=1 -c -o src/encoder_plugin.o src/encoder_plugin.c
cc -Wall -Wextra -g -O3   -c -o src/filter.o src/filter.c
cc -Wall -Wextra -g -O3  -DFILTER_PLUGIN_AVFILTER=1 -c -o src/filter_plugin.o src/filter_plugin.c
cc -Wall -Wextra -g -O3   -c -o src/filter_plugin_buffer.o src/filter_plugin_buffer.c
cc -Wall -Wextra -g -O3   -c -o src/filter_plugin_passthrough.o src/filter_plugin_passthrough.c
cc -Wall -Wextra -g -O3   -c -o src/frame.o src/frame.c
cc -Wall -Wextra -g -O3   -c -o src/hls.o src/hls.c
cc -Wall -Wextra -g -O3   -c -o src/ich_time.o src/ich_time.c
cc -Wall -Wextra -g -O3   -c -o src/id3.o src/id3.c
cc -Wall -Wextra -g -O3   -c -o src/input.o src/input.c
cc -Wall -Wextra -g -O3 -DINPUT_PLUGIN_CURL=1 -c -o src/input_plugin.o src/input_plugin.c
cc -Wall -Wextra -g -O3   -c -o src/input_plugin_file.o src/input_plugin_file.c
cc -Wall -Wextra -g -O3   -c -o src/input_plugin_stdin.o src/input_plugin_stdin.c
cc -Wall -Wextra -g -O3   -c -o src/muxer.o src/muxer.c
cc -Wall -Wextra -g -O3   -c -o src/muxer_plugin.o src/muxer_plugin.c
cc -Wall -Wextra -g -O3   -c -o src/muxer_plugin_fmp4.o src/muxer_plugin_fmp4.c
cc -Wall -Wextra -g -O3   -c -o src/muxer_plugin_packedaudio.o src/muxer_plugin_packedaudio.c
cc -Wall -Wextra -g -O3   -c -o src/output.o src/output.c
cc -Wall -Wextra -g -O3 -DOUTPUT_PLUGIN_CURL=1 -c -o src/output_plugin.o src/output_plugin.c
cc -Wall -Wextra -g -O3   -c -o src/output_plugin_file.o src/output_plugin_file.c
cc -Wall -Wextra -g -O3   -c -o src/output_plugin_stdout.o src/output_plugin_stdout.c
cc -Wall -Wextra -g -O3   -c -o src/output_plugin_folder.o src/output_plugin_folder.c
cc -Wall -Wextra -g -O3   -c -o src/packet.o src/packet.c
cc -Wall -Wextra -g -O3   -c -o src/samplefmt.o src/samplefmt.c
cc -Wall -Wextra -g -O3   -c -o src/source.o src/source.c
cc -Wall -Wextra -g -O3   -c -o src/sourcelist.o src/sourcelist.c
cc -Wall -Wextra -g -O3   -c -o src/source_sync.o src/source_sync.c
cc -Wall -Wextra -g -O3   -c -o src/str.o src/str.c
cc -Wall -Wextra -g -O3   -c -o src/strbuf.o src/strbuf.c
cc -Wall -Wextra -g -O3   -c -o src/tag.o src/tag.c
cc -Wall -Wextra -g -O3   -c -o src/tagmap.o src/tagmap.c
cc -Wall -Wextra -g -O3   -c -o src/tagmap_default.o src/tagmap_default.c
cc -Wall -Wextra -g -O3 -c -o src/thread.o src/thread.c
In file included from src/thread.c:4:0:
src/thread.h: In function ‘thread_create’:
src/thread.h:696:79: warning: unused parameter ‘stack_size’ [-Wunused-parameter]
 thread_ptr_t thread_create( int (*thread_proc)( void* ), void* user_data, int stack_size )
                                                                               ^~~~~~~~~~
src/thread.h: In function ‘thread_signal_init’:
src/thread.h:895:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
     #pragma warning( push )

src/thread.h:896:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
     #pragma warning( disable: 4214 ) // nonstandard extension used: bit field types other than int

In file included from src/thread.c:4:0:
src/thread.h:898:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
     #pragma warning( pop )

src/thread.h: In function ‘thread_timer_init’:
src/thread.h:1375:41: warning: unused parameter ‘timer’ [-Wunused-parameter]
 void thread_timer_init( thread_timer_t* timer )
                                         ^~~~~
src/thread.h: In function ‘thread_timer_term’:
src/thread.h:1401:41: warning: unused parameter ‘timer’ [-Wunused-parameter]
 void thread_timer_term( thread_timer_t* timer )
                                         ^~~~~
src/thread.h: In function ‘thread_timer_wait’:
src/thread.h:1421:41: warning: unused parameter ‘timer’ [-Wunused-parameter]
 void thread_timer_wait( thread_timer_t* timer, THREAD_U64 nanoseconds )
                                         ^~~~~
src/thread.h: In function ‘thread_tls_create’:
src/thread.h:1460:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             return (thread_tls_t) tls;
                    ^
cc -Wall -Wextra -g -O3 -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -c -o src/filter_plugin_avfilter.o src/filter_plugin_avfilter.c
cc -Wall -Wextra -g -O3 -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -c -o src/encoder_plugin_avcodec.o src/encoder_plugin_avcodec.c
In file included from src/encoder_plugin_avcodec.c:4:0:
src/avpacket_utils.h:8:10: fatal error: libavcodec/packet.h: No such file or directory
 #include <libavcodec/packet.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:261: recipe for target 'src/encoder_plugin_avcodec.o' failed
make: *** [src/encoder_plugin_avcodec.o] Error 1

**Comment by jprjr** [comment]
Don't reach out to me outside of GitHub issues.

**Comment by jprjr** [comment]
I've updated the Wiki to list required dependencies and some basic build instructions - https://github.com/jprjr/icecast-hls/wiki/Documentation#dependencies

Additionally, all my testing had been with newer ffmpeg releases (ffmpeg 4.4+), Ubuntu 18.04 ships with ffmpeg 3.4.

I downloaded and tested against each ffmpeg version down to 2.8, the application should now compile and run against older versions.
